[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-experimental_warm
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-experimental_warm
GtkTheme=oomox-experimental_warm
IconTheme=oomox-experimental_warm
MetacityTheme=oomox-experimental_warm
